[app]
backend_url = "http://127.0.0.1:3003"

[solana]
rpc_url = ""
program_id = "28bk4vaL8MfDZ5xbcitXNJjYbiRUaR3mnK21RnAjT8Ya"
bundlr_keypair = ""
bundlr_url = "https://devnet.bundlr.network/"

[package.metadata.leptos]
output-name = "replayer-fe"
site-root = "target/site"
site-addr = "127.0.0.1:3005"
