[app]
backend_url = "some"

[solana]
rpc_url = "http://127.0.0.1:8899"
program_id = "3L4ZDN7REkTk97ybn5FS4NUBMmcbQQQjQbKH6kET595c"

[package.metadata.leptos]
output-name = "replayer-fe"
site-root = "target/site"
site-addr = "127.0.0.1:3005"
